---
role_name_check: 1

dependency:
  name: galaxy

driver:
  name: molecule_hetznercloud

platforms:
  - name: ipxe-ca-jammy-1
    image: ubuntu-22.04
    location: fsn1

provisioner:
  name: ansible
  options:
    D: true
  playbooks:
    converge: converge.yml
